version: "3.7"

services:
  nginx-balancer:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./nginx:/etc/nginx"
  node-app1:
    image: nodejs-app
    environment:
      - APPID=1111
  node-app2:
    image: nodejs-app
    environment:
      - APPID=2222