version: "3.7"

services:
  nginx-balancer:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - "nginx.conf:/etc/nginx/nginx.conf"
  node-app1:
    image: node-application
    environment:
      - APPID=1111
  node-app2:
    image: node-application
    environment:
      - APPID=2222